### ISSUE TITLE
无耻之徒

### ISSUE THREAD

**Issue by singer01** [Chihaya-Yuka/SQLJson#1]
打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！

**Comment by Chihaya-Yuka** [comment]
Github is not a place for promoting political views.

**Comment by zhiziqxd** [comment]
?

**Comment by singer01** [comment]
> ?

你们，攻击GPCR的那些人，说的这些那可以说是鸡蛋里面挑骨头，挑来挑去。采用了没有的给我捏造，小事情给我夸大，别人的加在我头上，用这样的方法来制造了这起大大的冤案。你们开了这个头，好，后人就会群起而校之。我所干的这一切，包括你们现在在台上的绝大多数人都曾经异口同声地拥护过，参加过，你们又怎样解释你们当年的行为呢？我就是和尚打伞——无法无天。大不了杀头。我是孙悟空，我能变几个脑袋，你砍几个，我长几个。杀我灭口，光荣之甚。这就是我的回答！
